/* tslint:disable */
/* eslint-disable */
/**
 * Traccar
 * Traccar GPS tracking server API documentation. To use the API you need to have a server instance. For testing purposes you can use one of free [demo servers](https://www.traccar.org/demo-server/). For production use you can install your own server or get a [subscription service](https://www.traccar.org/product/tracking-server/).
 *
 * OpenAPI spec version: 4.11
 * Contact: support@traccar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Device
 */
export interface Device {
    /**
     * 
     * @type {number}
     * @memberof Device
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    uniqueId?: any;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    status?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Device
     */
    disabled?: any;
    /**
     * in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
     * @type {Date}
     * @memberof Device
     */
    lastUpdate?: any;
    /**
     * 
     * @type {number}
     * @memberof Device
     */
    positionId?: any;
    /**
     * 
     * @type {number}
     * @memberof Device
     */
    groupId?: any;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    phone?: any;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    model?: any;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    contact?: any;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    category?: any;
    /**
     * 
     * @type {Array&lt;number&gt;}
     * @memberof Device
     */
    geofenceIds?: any;
    /**
     * 
     * @type {any}
     * @memberof Device
     */
    attributes?: any;
}
