/* tslint:disable */
/* eslint-disable */
/**
 * Traccar
 * Traccar GPS tracking server API documentation. To use the API you need to have a server instance. For testing purposes you can use one of free [demo servers](https://www.traccar.org/demo-server/). For production use you can install your own server or get a [subscription service](https://www.traccar.org/product/tracking-server/).
 *
 * OpenAPI spec version: 4.11
 * Contact: support@traccar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * This is a permission map that contain two object indexes. It is used to link/unlink objects. Order is important. Example: { deviceId:8, geofenceId: 16 }
 * @export
 * @interface Permission
 */
export interface Permission {
    /**
     * User Id, can be only first parameter
     * @type {number}
     * @memberof Permission
     */
    userId?: any;
    /**
     * Device Id, can be first parameter or second only in combination with userId
     * @type {number}
     * @memberof Permission
     */
    deviceId?: any;
    /**
     * Group Id, can be first parameter or second only in combination with userId
     * @type {number}
     * @memberof Permission
     */
    groupId?: any;
    /**
     * Geofence Id, can be second parameter only
     * @type {number}
     * @memberof Permission
     */
    geofenceId?: any;
    /**
     * Calendar Id, can be second parameter only and only in combination with userId
     * @type {number}
     * @memberof Permission
     */
    calendarId?: any;
    /**
     * Computed Attribute Id, can be second parameter only
     * @type {number}
     * @memberof Permission
     */
    attributeId?: any;
    /**
     * Driver Id, can be second parameter only
     * @type {number}
     * @memberof Permission
     */
    driverId?: any;
    /**
     * User Id, can be second parameter only and only in combination with userId
     * @type {number}
     * @memberof Permission
     */
    managedUserId?: any;
}
