/* tslint:disable */
/* eslint-disable */
/**
 * Traccar
 * Traccar GPS tracking server API documentation. To use the API you need to have a server instance. For testing purposes you can use one of free [demo servers](https://www.traccar.org/demo-server/). For production use you can install your own server or get a [subscription service](https://www.traccar.org/product/tracking-server/).
 *
 * OpenAPI spec version: 4.11
 * Contact: support@traccar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Position
 */
export interface Position {
    /**
     * 
     * @type {number}
     * @memberof Position
     */
    id?: any;
    /**
     * 
     * @type {number}
     * @memberof Position
     */
    deviceId?: any;
    /**
     * 
     * @type {string}
     * @memberof Position
     */
    protocol?: any;
    /**
     * in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
     * @type {Date}
     * @memberof Position
     */
    deviceTime?: any;
    /**
     * in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
     * @type {Date}
     * @memberof Position
     */
    fixTime?: any;
    /**
     * in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
     * @type {Date}
     * @memberof Position
     */
    serverTime?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Position
     */
    outdated?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Position
     */
    valid?: any;
    /**
     * 
     * @type {number}
     * @memberof Position
     */
    latitude?: any;
    /**
     * 
     * @type {number}
     * @memberof Position
     */
    longitude?: any;
    /**
     * 
     * @type {number}
     * @memberof Position
     */
    altitude?: any;
    /**
     * in knots
     * @type {number}
     * @memberof Position
     */
    speed?: any;
    /**
     * 
     * @type {number}
     * @memberof Position
     */
    course?: any;
    /**
     * 
     * @type {string}
     * @memberof Position
     */
    address?: any;
    /**
     * 
     * @type {number}
     * @memberof Position
     */
    accuracy?: any;
    /**
     * 
     * @type {any}
     * @memberof Position
     */
    network?: any;
    /**
     * 
     * @type {any}
     * @memberof Position
     */
    attributes?: any;
}
