/* tslint:disable */
/* eslint-disable */
/**
 * Traccar
 * Traccar GPS tracking server API documentation. To use the API you need to have a server instance. For testing purposes you can use one of free [demo servers](https://www.traccar.org/demo-server/). For production use you can install your own server or get a [subscription service](https://www.traccar.org/product/tracking-server/).
 *
 * OpenAPI spec version: 4.11
 * Contact: support@traccar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ReportTrips
 */
export interface ReportTrips {
    /**
     * 
     * @type {number}
     * @memberof ReportTrips
     */
    deviceId?: any;
    /**
     * 
     * @type {string}
     * @memberof ReportTrips
     */
    deviceName?: any;
    /**
     * in knots
     * @type {number}
     * @memberof ReportTrips
     */
    maxSpeed?: any;
    /**
     * in knots
     * @type {number}
     * @memberof ReportTrips
     */
    averageSpeed?: any;
    /**
     * in meters
     * @type {number}
     * @memberof ReportTrips
     */
    distance?: any;
    /**
     * in liters
     * @type {number}
     * @memberof ReportTrips
     */
    spentFuel?: any;
    /**
     * 
     * @type {number}
     * @memberof ReportTrips
     */
    duration?: any;
    /**
     * in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
     * @type {Date}
     * @memberof ReportTrips
     */
    startTime?: any;
    /**
     * 
     * @type {string}
     * @memberof ReportTrips
     */
    startAddress?: any;
    /**
     * 
     * @type {number}
     * @memberof ReportTrips
     */
    startLat?: any;
    /**
     * 
     * @type {number}
     * @memberof ReportTrips
     */
    startLon?: any;
    /**
     * in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
     * @type {Date}
     * @memberof ReportTrips
     */
    endTime?: any;
    /**
     * 
     * @type {string}
     * @memberof ReportTrips
     */
    endAddress?: any;
    /**
     * 
     * @type {number}
     * @memberof ReportTrips
     */
    endLat?: any;
    /**
     * 
     * @type {number}
     * @memberof ReportTrips
     */
    endLon?: any;
    /**
     * 
     * @type {number}
     * @memberof ReportTrips
     */
    driverUniqueId?: any;
    /**
     * 
     * @type {string}
     * @memberof ReportTrips
     */
    driverName?: any;
}
