/* tslint:disable */
/* eslint-disable */
/**
 * Traccar
 * Traccar GPS tracking server API documentation. To use the API you need to have a server instance. For testing purposes you can use one of free [demo servers](https://www.traccar.org/demo-server/). For production use you can install your own server or get a [subscription service](https://www.traccar.org/product/tracking-server/).
 *
 * OpenAPI spec version: 4.11
 * Contact: support@traccar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    phone?: any;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    readonly?: any;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    administrator?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    map?: any;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    latitude?: any;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    longitude?: any;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    zoom?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    password?: any;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    twelveHourFormat?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    coordinateFormat?: any;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    disabled?: any;
    /**
     * in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
     * @type {Date}
     * @memberof User
     */
    expirationTime?: any;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    deviceLimit?: any;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    userLimit?: any;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    deviceReadonly?: any;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    limitCommands?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    poiLayer?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    token?: any;
    /**
     * 
     * @type {any}
     * @memberof User
     */
    attributes?: any;
}
